// ─────────────────────────────────────────────────────────────
// Icon library · IconDefinition 126 筆（對齊 impl assets/definitions/IconDefinition.json）
//
// 單一來源：library 'svg' — phosphor SVG，CSS mask 載 project/assets/icons/phosphor/<glyph>.svg。
// 法幣 typeset 符號（原 id 100-205，library 'currency'）已於 2026-07 icon 池策展整批移除；
// 舊資料若殘留這些 id，由 impl 開機自癒重設為該池預設圖示。
// account tag：id 1-11（帳戶）+ 79/92（ambulance/planet 與 category 共用）+ 206-221（策展新增 16）
//              + 98-99（BTC/ETH 線稿）+ 222-230（法幣線稿 9）= 40
// category tag：id 12-97 + 231（baby，排 devices 後）+ 232（beer-stein，排 cigarette 後）= 88
// picker 顯示順序 = 本陣列順序（兩端 picker 按 tags 過濾後照序鋪格，預設 = 過濾後第一個）
// ─────────────────────────────────────────────────────────────

const ICON_LIBRARY = [
  { id:  1, uniqueName: 'ph-money'                  , library: 'svg', glyph: 'money'                  , tags: ['account'] },
  { id:  2, uniqueName: 'ph-coins'                  , library: 'svg', glyph: 'coins'                  , tags: ['account'] },
  { id:  3, uniqueName: 'ph-wallet'                 , library: 'svg', glyph: 'wallet'                 , tags: ['account'] },
  { id:  4, uniqueName: 'ph-piggy-bank'             , library: 'svg', glyph: 'piggy-bank'             , tags: ['account'] },
  { id:  5, uniqueName: 'ph-jar'                    , library: 'svg', glyph: 'jar'                    , tags: ['account'] },
  { id:  6, uniqueName: 'ph-gift'                   , library: 'svg', glyph: 'gift'                   , tags: ['account'] },
  { id:  7, uniqueName: 'ph-credit-card'            , library: 'svg', glyph: 'credit-card'            , tags: ['account'] },
  { id:  8, uniqueName: 'ph-contactless-payment'    , library: 'svg', glyph: 'contactless-payment'    , tags: ['account'] },
  { id:  9, uniqueName: 'ph-paypal-logo'            , library: 'svg', glyph: 'paypal-logo'            , tags: ['account'] },
  { id: 10, uniqueName: 'ph-archive'                , library: 'svg', glyph: 'archive'                , tags: ['account'] },
  { id: 11, uniqueName: 'ph-building'               , library: 'svg', glyph: 'building'               , tags: ['account'] },
  { id: 12, uniqueName: 'ph-bread'                  , library: 'svg', glyph: 'bread'                  , tags: ['category'] },
  { id: 13, uniqueName: 'ph-coffee'                 , library: 'svg', glyph: 'coffee'                 , tags: ['category'] },
  { id: 14, uniqueName: 'ph-acorn'                  , library: 'svg', glyph: 'acorn'                  , tags: ['category'] },
  { id: 15, uniqueName: 'ph-ice-cream'              , library: 'svg', glyph: 'ice-cream'              , tags: ['category'] },
  { id: 16, uniqueName: 'ph-martini'                , library: 'svg', glyph: 'martini'                , tags: ['category'] },
  { id: 17, uniqueName: 'ph-cake'                   , library: 'svg', glyph: 'cake'                   , tags: ['category'] },
  { id: 18, uniqueName: 'ph-person-simple-bike'     , library: 'svg', glyph: 'person-simple-bike'     , tags: ['category'] },
  { id: 19, uniqueName: 'ph-bicycle'                , library: 'svg', glyph: 'bicycle'                , tags: ['category'] },
  { id: 20, uniqueName: 'ph-moped'                  , library: 'svg', glyph: 'moped'                  , tags: ['category'] },
  { id: 21, uniqueName: 'ph-motorcycle'             , library: 'svg', glyph: 'motorcycle'             , tags: ['category'] },
  { id: 22, uniqueName: 'ph-car'                    , library: 'svg', glyph: 'car'                    , tags: ['category'] },
  { id: 23, uniqueName: 'ph-bus'                    , library: 'svg', glyph: 'bus'                    , tags: ['category'] },
  { id: 24, uniqueName: 'ph-train-simple'           , library: 'svg', glyph: 'train-simple'           , tags: ['category'] },
  { id: 25, uniqueName: 'ph-taxi'                   , library: 'svg', glyph: 'taxi'                   , tags: ['category'] },
  { id: 26, uniqueName: 'ph-anchor'                 , library: 'svg', glyph: 'anchor'                 , tags: ['category'] },
  { id: 27, uniqueName: 'ph-airplane-takeoff'       , library: 'svg', glyph: 'airplane-takeoff'       , tags: ['category'] },
  { id: 28, uniqueName: 'ph-shopping-cart'          , library: 'svg', glyph: 'shopping-cart'          , tags: ['category'] },
  { id: 29, uniqueName: 'ph-storefront'             , library: 'svg', glyph: 'storefront'             , tags: ['category'] },
  { id: 30, uniqueName: 'ph-dress'                  , library: 'svg', glyph: 'dress'                  , tags: ['category'] },
  { id: 31, uniqueName: 'ph-t-shirt'                , library: 'svg', glyph: 't-shirt'                , tags: ['category'] },
  { id: 32, uniqueName: 'ph-high-heel'              , library: 'svg', glyph: 'high-heel'              , tags: ['category'] },
  { id: 33, uniqueName: 'ph-watch'                  , library: 'svg', glyph: 'watch'                  , tags: ['category'] },
  { id: 34, uniqueName: 'ph-backpack'               , library: 'svg', glyph: 'backpack'               , tags: ['category'] },
  { id: 35, uniqueName: 'ph-pencil-simple'          , library: 'svg', glyph: 'pencil-simple'          , tags: ['category'] },
  { id: 36, uniqueName: 'ph-ruler'                  , library: 'svg', glyph: 'ruler'                  , tags: ['category'] },
  { id: 37, uniqueName: 'ph-phone'                  , library: 'svg', glyph: 'phone'                  , tags: ['category'] },
  { id: 38, uniqueName: 'ph-lightbulb'              , library: 'svg', glyph: 'lightbulb'              , tags: ['category'] },
  { id: 39, uniqueName: 'ph-plugs'                  , library: 'svg', glyph: 'plugs'                  , tags: ['category'] },
  { id: 40, uniqueName: 'ph-alarm'                  , library: 'svg', glyph: 'alarm'                  , tags: ['category'] },
  { id: 41, uniqueName: 'ph-umbrella-simple'        , library: 'svg', glyph: 'umbrella-simple'        , tags: ['category'] },
  { id: 42, uniqueName: 'ph-book'                   , library: 'svg', glyph: 'book'                   , tags: ['category'] },
  { id: 43, uniqueName: 'ph-projector-screen'       , library: 'svg', glyph: 'projector-screen'       , tags: ['category'] },
  { id: 44, uniqueName: 'ph-broom'                  , library: 'svg', glyph: 'broom'                  , tags: ['category'] },
  { id: 45, uniqueName: 'ph-wrench'                 , library: 'svg', glyph: 'wrench'                 , tags: ['category'] },
  { id: 46, uniqueName: 'ph-axe'                    , library: 'svg', glyph: 'axe'                    , tags: ['category'] },
  { id: 47, uniqueName: 'ph-car-battery'            , library: 'svg', glyph: 'car-battery'            , tags: ['category'] },
  { id: 48, uniqueName: 'ph-engine'                 , library: 'svg', glyph: 'engine'                 , tags: ['category'] },
  { id: 49, uniqueName: 'ph-toilet'                 , library: 'svg', glyph: 'toilet'                 , tags: ['category'] },
  { id: 50, uniqueName: 'ph-devices'                , library: 'svg', glyph: 'devices'                , tags: ['category'] },
  { id: 231, uniqueName: 'ph-baby'                  , library: 'svg', glyph: 'baby'                   , tags: ['category'] },
  { id: 51, uniqueName: 'ph-baby-carriage'          , library: 'svg', glyph: 'baby-carriage'          , tags: ['category'] },
  { id: 52, uniqueName: 'ph-armchair'               , library: 'svg', glyph: 'armchair'               , tags: ['category'] },
  { id: 53, uniqueName: 'ph-house'                  , library: 'svg', glyph: 'house'                  , tags: ['category'] },
  { id: 54, uniqueName: 'ph-music-notes-simple'     , library: 'svg', glyph: 'music-notes-simple'     , tags: ['category'] },
  { id: 55, uniqueName: 'ph-palette'                , library: 'svg', glyph: 'palette'                , tags: ['category'] },
  { id: 56, uniqueName: 'ph-camera'                 , library: 'svg', glyph: 'camera'                 , tags: ['category'] },
  { id: 57, uniqueName: 'ph-video-camera'           , library: 'svg', glyph: 'video-camera'           , tags: ['category'] },
  { id: 58, uniqueName: 'ph-ghost'                  , library: 'svg', glyph: 'ghost'                  , tags: ['category'] },
  { id: 59, uniqueName: 'ph-lego'                   , library: 'svg', glyph: 'lego'                   , tags: ['category'] },
  { id: 60, uniqueName: 'ph-game-controller'        , library: 'svg', glyph: 'game-controller'        , tags: ['category'] },
  { id: 61, uniqueName: 'ph-rocket-launch'          , library: 'svg', glyph: 'rocket-launch'          , tags: ['category'] },
  { id: 62, uniqueName: 'ph-barbell'                , library: 'svg', glyph: 'barbell'                , tags: ['category'] },
  { id: 63, uniqueName: 'ph-tennis-ball'            , library: 'svg', glyph: 'tennis-ball'            , tags: ['category'] },
  { id: 64, uniqueName: 'ph-basketball'             , library: 'svg', glyph: 'basketball'             , tags: ['category'] },
  { id: 65, uniqueName: 'ph-volleyball'             , library: 'svg', glyph: 'volleyball'             , tags: ['category'] },
  { id: 66, uniqueName: 'ph-baseball'               , library: 'svg', glyph: 'baseball'               , tags: ['category'] },
  { id: 67, uniqueName: 'ph-beach-ball'             , library: 'svg', glyph: 'beach-ball'             , tags: ['category'] },
  { id: 68, uniqueName: 'ph-ping-pong'              , library: 'svg', glyph: 'ping-pong'              , tags: ['category'] },
  { id: 69, uniqueName: 'ph-boxing-glove'           , library: 'svg', glyph: 'boxing-glove'           , tags: ['category'] },
  { id: 70, uniqueName: 'ph-football'               , library: 'svg', glyph: 'football'               , tags: ['category'] },
  { id: 71, uniqueName: 'ph-hockey'                 , library: 'svg', glyph: 'hockey'                 , tags: ['category'] },
  { id: 72, uniqueName: 'ph-person-simple-snowboard', library: 'svg', glyph: 'person-simple-snowboard', tags: ['category'] },
  { id: 73, uniqueName: 'ph-handshake'              , library: 'svg', glyph: 'handshake'              , tags: ['category'] },
  { id: 74, uniqueName: 'ph-hands-praying'          , library: 'svg', glyph: 'hands-praying'          , tags: ['category'] },
  { id: 75, uniqueName: 'ph-heart'                  , library: 'svg', glyph: 'heart'                  , tags: ['category'] },
  { id: 76, uniqueName: 'ph-pill'                   , library: 'svg', glyph: 'pill'                   , tags: ['category'] },
  { id: 77, uniqueName: 'ph-fire'                   , library: 'svg', glyph: 'fire'                   , tags: ['category'] },
  { id: 78, uniqueName: 'ph-fire-extinguisher'      , library: 'svg', glyph: 'fire-extinguisher'      , tags: ['category'] },
  { id: 79, uniqueName: 'ph-ambulance'              , library: 'svg', glyph: 'ambulance'              , tags: ['category', 'account'] },
  { id: 80, uniqueName: 'ph-clover'                 , library: 'svg', glyph: 'clover'                 , tags: ['category'] },
  { id: 81, uniqueName: 'ph-cactus'                 , library: 'svg', glyph: 'cactus'                 , tags: ['category'] },
  { id: 82, uniqueName: 'ph-tree'                   , library: 'svg', glyph: 'tree'                   , tags: ['category'] },
  { id: 83, uniqueName: 'ph-bird'                   , library: 'svg', glyph: 'bird'                   , tags: ['category'] },
  { id: 84, uniqueName: 'ph-cat'                    , library: 'svg', glyph: 'cat'                    , tags: ['category'] },
  { id: 85, uniqueName: 'ph-dog'                    , library: 'svg', glyph: 'dog'                    , tags: ['category'] },
  { id: 86, uniqueName: 'ph-bone'                   , library: 'svg', glyph: 'bone'                   , tags: ['category'] },
  { id: 87, uniqueName: 'ph-chart-line'             , library: 'svg', glyph: 'chart-line'             , tags: ['category'] },
  { id: 88, uniqueName: 'ph-bank'                   , library: 'svg', glyph: 'bank'                   , tags: ['category'] },
  { id: 89, uniqueName: 'ph-scales'                 , library: 'svg', glyph: 'scales'                 , tags: ['category'] },
  { id: 90, uniqueName: 'ph-pi'                     , library: 'svg', glyph: 'pi'                     , tags: ['category'] },
  { id: 91, uniqueName: 'ph-crown-simple'           , library: 'svg', glyph: 'crown-simple'           , tags: ['category'] },
  { id: 92, uniqueName: 'ph-planet'                 , library: 'svg', glyph: 'planet'                 , tags: ['category', 'account'] },
  { id: 93, uniqueName: 'ph-flying-saucer'          , library: 'svg', glyph: 'flying-saucer'          , tags: ['category'] },
  { id: 94, uniqueName: 'ph-rainbow'                , library: 'svg', glyph: 'rainbow'                , tags: ['category'] },
  { id: 95, uniqueName: 'ph-cigarette'              , library: 'svg', glyph: 'cigarette'              , tags: ['category'] },
  { id: 232, uniqueName: 'ph-beer-stein'            , library: 'svg', glyph: 'beer-stein'             , tags: ['category'] },
  { id: 96, uniqueName: 'ph-biohazard'              , library: 'svg', glyph: 'biohazard'              , tags: ['category'] },
  { id: 97, uniqueName: 'ph-trash-simple'           , library: 'svg', glyph: 'trash-simple'           , tags: ['category'] },
  // ── 帳戶擴充 · 2026-07 策展（旅行/機構/趣味 16 + 幣別線稿 11）──
  { id: 206, uniqueName: 'ph-suitcase-rolling'      , library: 'svg', glyph: 'suitcase-rolling'       , tags: ['account'] },
  { id: 207, uniqueName: 'ph-suitcase'              , library: 'svg', glyph: 'suitcase'               , tags: ['account'] },
  { id: 208, uniqueName: 'ph-airplane'              , library: 'svg', glyph: 'airplane'               , tags: ['account'] },
  { id: 209, uniqueName: 'ph-atom'                  , library: 'svg', glyph: 'atom'                   , tags: ['account'] },
  { id: 210, uniqueName: 'ph-cash-register'         , library: 'svg', glyph: 'cash-register'          , tags: ['account'] },
  { id: 211, uniqueName: 'ph-club'                  , library: 'svg', glyph: 'club'                   , tags: ['account'] },
  { id: 212, uniqueName: 'ph-database'              , library: 'svg', glyph: 'database'               , tags: ['account'] },
  { id: 213, uniqueName: 'ph-detective'             , library: 'svg', glyph: 'detective'              , tags: ['account'] },
  { id: 214, uniqueName: 'ph-dna'                   , library: 'svg', glyph: 'dna'                    , tags: ['account'] },
  { id: 215, uniqueName: 'ph-factory'               , library: 'svg', glyph: 'factory'                , tags: ['account'] },
  { id: 216, uniqueName: 'ph-hourglass-simple'      , library: 'svg', glyph: 'hourglass-simple'       , tags: ['account'] },
  { id: 217, uniqueName: 'ph-infinity'              , library: 'svg', glyph: 'infinity'               , tags: ['account'] },
  { id: 218, uniqueName: 'ph-island'                , library: 'svg', glyph: 'island'                 , tags: ['account'] },
  { id: 219, uniqueName: 'ph-map-pin-line'          , library: 'svg', glyph: 'map-pin-line'           , tags: ['account'] },
  { id: 220, uniqueName: 'ph-puzzle-piece'          , library: 'svg', glyph: 'puzzle-piece'           , tags: ['account'] },
  { id: 221, uniqueName: 'ph-shield'                , library: 'svg', glyph: 'shield'                 , tags: ['account'] },
  // BTC/ETH 線稿沿用既有 id 98/99（既有資料引用不動），僅移到策展順位
  { id: 98, uniqueName: 'ph-currency-btc'           , library: 'svg', glyph: 'currency-btc'           , tags: ['account'] },
  { id: 99, uniqueName: 'ph-currency-eth'           , library: 'svg', glyph: 'currency-eth'           , tags: ['account'] },
  { id: 222, uniqueName: 'ph-currency-dollar'       , library: 'svg', glyph: 'currency-dollar'        , tags: ['account'] },
  { id: 223, uniqueName: 'ph-currency-eur'          , library: 'svg', glyph: 'currency-eur'           , tags: ['account'] },
  { id: 224, uniqueName: 'ph-currency-gbp'          , library: 'svg', glyph: 'currency-gbp'           , tags: ['account'] },
  { id: 225, uniqueName: 'ph-currency-jpy'          , library: 'svg', glyph: 'currency-jpy'           , tags: ['account'] },
  { id: 226, uniqueName: 'ph-currency-krw'          , library: 'svg', glyph: 'currency-krw'           , tags: ['account'] },
  { id: 227, uniqueName: 'ph-currency-inr'          , library: 'svg', glyph: 'currency-inr'           , tags: ['account'] },
  { id: 228, uniqueName: 'ph-currency-kzt'          , library: 'svg', glyph: 'currency-kzt'           , tags: ['account'] },
  { id: 229, uniqueName: 'ph-currency-ngn'          , library: 'svg', glyph: 'currency-ngn'           , tags: ['account'] },
  { id: 230, uniqueName: 'ph-currency-cny'          , library: 'svg', glyph: 'currency-cny'           , tags: ['account'] },
];
const ICON_BY_ID = Object.fromEntries(ICON_LIBRARY.map(i => [i.id, i]));

Object.assign(window, { ICON_LIBRARY, ICON_BY_ID });
