// ─────────────────────────────────────────────────────────────
// Icon library · IconDefinition 205 筆（對齊 impl assets/definitions/IconDefinition.json）
//
// 兩種來源：
//   library 'svg'      — phosphor SVG，CSS mask 載 project/assets/icons/phosphor/<glyph>.svg
//   library 'currency' — 幣別符號，glyph = 幣別代碼，symbol 由 CURRENCY_SYMBOLS_ALL 推導、用文字排版
// account tag：id 1-11（帳戶）+ 98-99（BTC/ETH 線稿）+ 100-205（106 法幣符號）= 119；
// category tag：id 12-97。
// ─────────────────────────────────────────────────────────────

const ICON_LIBRARY = [
  { id:  1, uniqueName: 'ph-money'                  , library: 'svg', glyph: 'money'                  , tags: ['account'] },
  { id:  2, uniqueName: 'ph-coins'                  , library: 'svg', glyph: 'coins'                  , tags: ['account'] },
  { id:  3, uniqueName: 'ph-wallet'                 , library: 'svg', glyph: 'wallet'                 , tags: ['account'] },
  { id:  4, uniqueName: 'ph-piggy-bank'             , library: 'svg', glyph: 'piggy-bank'             , tags: ['account'] },
  { id:  5, uniqueName: 'ph-jar'                    , library: 'svg', glyph: 'jar'                    , tags: ['account'] },
  { id:  6, uniqueName: 'ph-gift'                   , library: 'svg', glyph: 'gift'                   , tags: ['account'] },
  { id:  7, uniqueName: 'ph-credit-card'            , library: 'svg', glyph: 'credit-card'            , tags: ['account'] },
  { id:  8, uniqueName: 'ph-contactless-payment'    , library: 'svg', glyph: 'contactless-payment'    , tags: ['account'] },
  { id:  9, uniqueName: 'ph-paypal-logo'            , library: 'svg', glyph: 'paypal-logo'            , tags: ['account'] },
  { id: 10, uniqueName: 'ph-archive'                , library: 'svg', glyph: 'archive'                , tags: ['account'] },
  { id: 11, uniqueName: 'ph-building'               , library: 'svg', glyph: 'building'               , tags: ['account'] },
  { id: 12, uniqueName: 'ph-bread'                  , library: 'svg', glyph: 'bread'                  , tags: ['category'] },
  { id: 13, uniqueName: 'ph-coffee'                 , library: 'svg', glyph: 'coffee'                 , tags: ['category'] },
  { id: 14, uniqueName: 'ph-acorn'                  , library: 'svg', glyph: 'acorn'                  , tags: ['category'] },
  { id: 15, uniqueName: 'ph-ice-cream'              , library: 'svg', glyph: 'ice-cream'              , tags: ['category'] },
  { id: 16, uniqueName: 'ph-martini'                , library: 'svg', glyph: 'martini'                , tags: ['category'] },
  { id: 17, uniqueName: 'ph-cake'                   , library: 'svg', glyph: 'cake'                   , tags: ['category'] },
  { id: 18, uniqueName: 'ph-person-simple-bike'     , library: 'svg', glyph: 'person-simple-bike'     , tags: ['category'] },
  { id: 19, uniqueName: 'ph-bicycle'                , library: 'svg', glyph: 'bicycle'                , tags: ['category'] },
  { id: 20, uniqueName: 'ph-moped'                  , library: 'svg', glyph: 'moped'                  , tags: ['category'] },
  { id: 21, uniqueName: 'ph-motorcycle'             , library: 'svg', glyph: 'motorcycle'             , tags: ['category'] },
  { id: 22, uniqueName: 'ph-car'                    , library: 'svg', glyph: 'car'                    , tags: ['category'] },
  { id: 23, uniqueName: 'ph-bus'                    , library: 'svg', glyph: 'bus'                    , tags: ['category'] },
  { id: 24, uniqueName: 'ph-train-simple'           , library: 'svg', glyph: 'train-simple'           , tags: ['category'] },
  { id: 25, uniqueName: 'ph-taxi'                   , library: 'svg', glyph: 'taxi'                   , tags: ['category'] },
  { id: 26, uniqueName: 'ph-anchor'                 , library: 'svg', glyph: 'anchor'                 , tags: ['category'] },
  { id: 27, uniqueName: 'ph-airplane-takeoff'       , library: 'svg', glyph: 'airplane-takeoff'       , tags: ['category'] },
  { id: 28, uniqueName: 'ph-shopping-cart'          , library: 'svg', glyph: 'shopping-cart'          , tags: ['category'] },
  { id: 29, uniqueName: 'ph-storefront'             , library: 'svg', glyph: 'storefront'             , tags: ['category'] },
  { id: 30, uniqueName: 'ph-dress'                  , library: 'svg', glyph: 'dress'                  , tags: ['category'] },
  { id: 31, uniqueName: 'ph-t-shirt'                , library: 'svg', glyph: 't-shirt'                , tags: ['category'] },
  { id: 32, uniqueName: 'ph-high-heel'              , library: 'svg', glyph: 'high-heel'              , tags: ['category'] },
  { id: 33, uniqueName: 'ph-watch'                  , library: 'svg', glyph: 'watch'                  , tags: ['category'] },
  { id: 34, uniqueName: 'ph-backpack'               , library: 'svg', glyph: 'backpack'               , tags: ['category'] },
  { id: 35, uniqueName: 'ph-pencil-simple'          , library: 'svg', glyph: 'pencil-simple'          , tags: ['category'] },
  { id: 36, uniqueName: 'ph-ruler'                  , library: 'svg', glyph: 'ruler'                  , tags: ['category'] },
  { id: 37, uniqueName: 'ph-phone'                  , library: 'svg', glyph: 'phone'                  , tags: ['category'] },
  { id: 38, uniqueName: 'ph-lightbulb'              , library: 'svg', glyph: 'lightbulb'              , tags: ['category'] },
  { id: 39, uniqueName: 'ph-plugs'                  , library: 'svg', glyph: 'plugs'                  , tags: ['category'] },
  { id: 40, uniqueName: 'ph-alarm'                  , library: 'svg', glyph: 'alarm'                  , tags: ['category'] },
  { id: 41, uniqueName: 'ph-umbrella-simple'        , library: 'svg', glyph: 'umbrella-simple'        , tags: ['category'] },
  { id: 42, uniqueName: 'ph-book'                   , library: 'svg', glyph: 'book'                   , tags: ['category'] },
  { id: 43, uniqueName: 'ph-projector-screen'       , library: 'svg', glyph: 'projector-screen'       , tags: ['category'] },
  { id: 44, uniqueName: 'ph-broom'                  , library: 'svg', glyph: 'broom'                  , tags: ['category'] },
  { id: 45, uniqueName: 'ph-wrench'                 , library: 'svg', glyph: 'wrench'                 , tags: ['category'] },
  { id: 46, uniqueName: 'ph-axe'                    , library: 'svg', glyph: 'axe'                    , tags: ['category'] },
  { id: 47, uniqueName: 'ph-car-battery'            , library: 'svg', glyph: 'car-battery'            , tags: ['category'] },
  { id: 48, uniqueName: 'ph-engine'                 , library: 'svg', glyph: 'engine'                 , tags: ['category'] },
  { id: 49, uniqueName: 'ph-toilet'                 , library: 'svg', glyph: 'toilet'                 , tags: ['category'] },
  { id: 50, uniqueName: 'ph-devices'                , library: 'svg', glyph: 'devices'                , tags: ['category'] },
  { id: 51, uniqueName: 'ph-baby-carriage'          , library: 'svg', glyph: 'baby-carriage'          , tags: ['category'] },
  { id: 52, uniqueName: 'ph-armchair'               , library: 'svg', glyph: 'armchair'               , tags: ['category'] },
  { id: 53, uniqueName: 'ph-house'                  , library: 'svg', glyph: 'house'                  , tags: ['category'] },
  { id: 54, uniqueName: 'ph-music-notes-simple'     , library: 'svg', glyph: 'music-notes-simple'     , tags: ['category'] },
  { id: 55, uniqueName: 'ph-palette'                , library: 'svg', glyph: 'palette'                , tags: ['category'] },
  { id: 56, uniqueName: 'ph-camera'                 , library: 'svg', glyph: 'camera'                 , tags: ['category'] },
  { id: 57, uniqueName: 'ph-video-camera'           , library: 'svg', glyph: 'video-camera'           , tags: ['category'] },
  { id: 58, uniqueName: 'ph-ghost'                  , library: 'svg', glyph: 'ghost'                  , tags: ['category'] },
  { id: 59, uniqueName: 'ph-lego'                   , library: 'svg', glyph: 'lego'                   , tags: ['category'] },
  { id: 60, uniqueName: 'ph-game-controller'        , library: 'svg', glyph: 'game-controller'        , tags: ['category'] },
  { id: 61, uniqueName: 'ph-rocket-launch'          , library: 'svg', glyph: 'rocket-launch'          , tags: ['category'] },
  { id: 62, uniqueName: 'ph-barbell'                , library: 'svg', glyph: 'barbell'                , tags: ['category'] },
  { id: 63, uniqueName: 'ph-tennis-ball'            , library: 'svg', glyph: 'tennis-ball'            , tags: ['category'] },
  { id: 64, uniqueName: 'ph-basketball'             , library: 'svg', glyph: 'basketball'             , tags: ['category'] },
  { id: 65, uniqueName: 'ph-volleyball'             , library: 'svg', glyph: 'volleyball'             , tags: ['category'] },
  { id: 66, uniqueName: 'ph-baseball'               , library: 'svg', glyph: 'baseball'               , tags: ['category'] },
  { id: 67, uniqueName: 'ph-beach-ball'             , library: 'svg', glyph: 'beach-ball'             , tags: ['category'] },
  { id: 68, uniqueName: 'ph-ping-pong'              , library: 'svg', glyph: 'ping-pong'              , tags: ['category'] },
  { id: 69, uniqueName: 'ph-boxing-glove'           , library: 'svg', glyph: 'boxing-glove'           , tags: ['category'] },
  { id: 70, uniqueName: 'ph-football'               , library: 'svg', glyph: 'football'               , tags: ['category'] },
  { id: 71, uniqueName: 'ph-hockey'                 , library: 'svg', glyph: 'hockey'                 , tags: ['category'] },
  { id: 72, uniqueName: 'ph-person-simple-snowboard', library: 'svg', glyph: 'person-simple-snowboard', tags: ['category'] },
  { id: 73, uniqueName: 'ph-handshake'              , library: 'svg', glyph: 'handshake'              , tags: ['category'] },
  { id: 74, uniqueName: 'ph-hands-praying'          , library: 'svg', glyph: 'hands-praying'          , tags: ['category'] },
  { id: 75, uniqueName: 'ph-heart'                  , library: 'svg', glyph: 'heart'                  , tags: ['category'] },
  { id: 76, uniqueName: 'ph-pill'                   , library: 'svg', glyph: 'pill'                   , tags: ['category'] },
  { id: 77, uniqueName: 'ph-fire'                   , library: 'svg', glyph: 'fire'                   , tags: ['category'] },
  { id: 78, uniqueName: 'ph-fire-extinguisher'      , library: 'svg', glyph: 'fire-extinguisher'      , tags: ['category'] },
  { id: 79, uniqueName: 'ph-ambulance'              , library: 'svg', glyph: 'ambulance'              , tags: ['category'] },
  { id: 80, uniqueName: 'ph-clover'                 , library: 'svg', glyph: 'clover'                 , tags: ['category'] },
  { id: 81, uniqueName: 'ph-cactus'                 , library: 'svg', glyph: 'cactus'                 , tags: ['category'] },
  { id: 82, uniqueName: 'ph-tree'                   , library: 'svg', glyph: 'tree'                   , tags: ['category'] },
  { id: 83, uniqueName: 'ph-bird'                   , library: 'svg', glyph: 'bird'                   , tags: ['category'] },
  { id: 84, uniqueName: 'ph-cat'                    , library: 'svg', glyph: 'cat'                    , tags: ['category'] },
  { id: 85, uniqueName: 'ph-dog'                    , library: 'svg', glyph: 'dog'                    , tags: ['category'] },
  { id: 86, uniqueName: 'ph-bone'                   , library: 'svg', glyph: 'bone'                   , tags: ['category'] },
  { id: 87, uniqueName: 'ph-chart-line'             , library: 'svg', glyph: 'chart-line'             , tags: ['category'] },
  { id: 88, uniqueName: 'ph-bank'                   , library: 'svg', glyph: 'bank'                   , tags: ['category'] },
  { id: 89, uniqueName: 'ph-scales'                 , library: 'svg', glyph: 'scales'                 , tags: ['category'] },
  { id: 90, uniqueName: 'ph-pi'                     , library: 'svg', glyph: 'pi'                     , tags: ['category'] },
  { id: 91, uniqueName: 'ph-crown-simple'           , library: 'svg', glyph: 'crown-simple'           , tags: ['category'] },
  { id: 92, uniqueName: 'ph-planet'                 , library: 'svg', glyph: 'planet'                 , tags: ['category'] },
  { id: 93, uniqueName: 'ph-flying-saucer'          , library: 'svg', glyph: 'flying-saucer'          , tags: ['category'] },
  { id: 94, uniqueName: 'ph-rainbow'                , library: 'svg', glyph: 'rainbow'                , tags: ['category'] },
  { id: 95, uniqueName: 'ph-cigarette'              , library: 'svg', glyph: 'cigarette'              , tags: ['category'] },
  { id: 96, uniqueName: 'ph-biohazard'              , library: 'svg', glyph: 'biohazard'              , tags: ['category'] },
  { id: 97, uniqueName: 'ph-trash-simple'           , library: 'svg', glyph: 'trash-simple'           , tags: ['category'] },
  // ── 幣別 icon · BTC/ETH 線稿 + 法幣 typeset 符號（account tag，對齊 impl IconDefinition）──
  { id: 98, uniqueName: 'ph-currency-btc', library: 'svg', glyph: 'currency-btc', tags: ['account'] },
  { id: 99, uniqueName: 'ph-currency-eth', library: 'svg', glyph: 'currency-eth', tags: ['account'] },
  { id: 100, uniqueName: 'cur-aed', library: 'currency', glyph: 'AED', tags: ['account'] },
  { id: 101, uniqueName: 'cur-afn', library: 'currency', glyph: 'AFN', tags: ['account'] },
  { id: 102, uniqueName: 'cur-all', library: 'currency', glyph: 'ALL', tags: ['account'] },
  { id: 103, uniqueName: 'cur-amd', library: 'currency', glyph: 'AMD', tags: ['account'] },
  { id: 104, uniqueName: 'cur-ang', library: 'currency', glyph: 'ANG', tags: ['account'] },
  { id: 105, uniqueName: 'cur-aoa', library: 'currency', glyph: 'AOA', tags: ['account'] },
  { id: 106, uniqueName: 'cur-usd', library: 'currency', glyph: 'USD', tags: ['account'] },
  { id: 107, uniqueName: 'cur-azn', library: 'currency', glyph: 'AZN', tags: ['account'] },
  { id: 108, uniqueName: 'cur-bam', library: 'currency', glyph: 'BAM', tags: ['account'] },
  { id: 109, uniqueName: 'cur-bdt', library: 'currency', glyph: 'BDT', tags: ['account'] },
  { id: 110, uniqueName: 'cur-bgn', library: 'currency', glyph: 'BGN', tags: ['account'] },
  { id: 111, uniqueName: 'cur-bhd', library: 'currency', glyph: 'BHD', tags: ['account'] },
  { id: 112, uniqueName: 'cur-bif', library: 'currency', glyph: 'BIF', tags: ['account'] },
  { id: 113, uniqueName: 'cur-bob', library: 'currency', glyph: 'BOB', tags: ['account'] },
  { id: 114, uniqueName: 'cur-brl', library: 'currency', glyph: 'BRL', tags: ['account'] },
  { id: 115, uniqueName: 'cur-btn', library: 'currency', glyph: 'BTN', tags: ['account'] },
  { id: 116, uniqueName: 'cur-bwp', library: 'currency', glyph: 'BWP', tags: ['account'] },
  { id: 117, uniqueName: 'cur-byn', library: 'currency', glyph: 'BYN', tags: ['account'] },
  { id: 118, uniqueName: 'cur-cdf', library: 'currency', glyph: 'CDF', tags: ['account'] },
  { id: 119, uniqueName: 'cur-chf', library: 'currency', glyph: 'CHF', tags: ['account'] },
  { id: 120, uniqueName: 'cur-jpy', library: 'currency', glyph: 'JPY', tags: ['account'] },
  { id: 121, uniqueName: 'cur-crc', library: 'currency', glyph: 'CRC', tags: ['account'] },
  { id: 122, uniqueName: 'cur-czk', library: 'currency', glyph: 'CZK', tags: ['account'] },
  { id: 123, uniqueName: 'cur-djf', library: 'currency', glyph: 'DJF', tags: ['account'] },
  { id: 124, uniqueName: 'cur-sek', library: 'currency', glyph: 'SEK', tags: ['account'] },
  { id: 125, uniqueName: 'cur-dop', library: 'currency', glyph: 'DOP', tags: ['account'] },
  { id: 126, uniqueName: 'cur-dzd', library: 'currency', glyph: 'DZD', tags: ['account'] },
  { id: 127, uniqueName: 'cur-egp', library: 'currency', glyph: 'EGP', tags: ['account'] },
  { id: 128, uniqueName: 'cur-ern', library: 'currency', glyph: 'ERN', tags: ['account'] },
  { id: 129, uniqueName: 'cur-eur', library: 'currency', glyph: 'EUR', tags: ['account'] },
  { id: 130, uniqueName: 'cur-gbp', library: 'currency', glyph: 'GBP', tags: ['account'] },
  { id: 131, uniqueName: 'cur-gel', library: 'currency', glyph: 'GEL', tags: ['account'] },
  { id: 132, uniqueName: 'cur-ghs', library: 'currency', glyph: 'GHS', tags: ['account'] },
  { id: 133, uniqueName: 'cur-gmd', library: 'currency', glyph: 'GMD', tags: ['account'] },
  { id: 134, uniqueName: 'cur-gnf', library: 'currency', glyph: 'GNF', tags: ['account'] },
  { id: 135, uniqueName: 'cur-gtq', library: 'currency', glyph: 'GTQ', tags: ['account'] },
  { id: 136, uniqueName: 'cur-hnl', library: 'currency', glyph: 'HNL', tags: ['account'] },
  { id: 137, uniqueName: 'cur-hrk', library: 'currency', glyph: 'HRK', tags: ['account'] },
  { id: 138, uniqueName: 'cur-htg', library: 'currency', glyph: 'HTG', tags: ['account'] },
  { id: 139, uniqueName: 'cur-huf', library: 'currency', glyph: 'HUF', tags: ['account'] },
  { id: 140, uniqueName: 'cur-idr', library: 'currency', glyph: 'IDR', tags: ['account'] },
  { id: 141, uniqueName: 'cur-ils', library: 'currency', glyph: 'ILS', tags: ['account'] },
  { id: 142, uniqueName: 'cur-inr', library: 'currency', glyph: 'INR', tags: ['account'] },
  { id: 143, uniqueName: 'cur-iqd', library: 'currency', glyph: 'IQD', tags: ['account'] },
  { id: 144, uniqueName: 'cur-irr', library: 'currency', glyph: 'IRR', tags: ['account'] },
  { id: 145, uniqueName: 'cur-jod', library: 'currency', glyph: 'JOD', tags: ['account'] },
  { id: 146, uniqueName: 'cur-kes', library: 'currency', glyph: 'KES', tags: ['account'] },
  { id: 147, uniqueName: 'cur-khr', library: 'currency', glyph: 'KHR', tags: ['account'] },
  { id: 148, uniqueName: 'cur-kmf', library: 'currency', glyph: 'KMF', tags: ['account'] },
  { id: 149, uniqueName: 'cur-krw', library: 'currency', glyph: 'KRW', tags: ['account'] },
  { id: 150, uniqueName: 'cur-kwd', library: 'currency', glyph: 'KWD', tags: ['account'] },
  { id: 151, uniqueName: 'cur-kzt', library: 'currency', glyph: 'KZT', tags: ['account'] },
  { id: 152, uniqueName: 'cur-lak', library: 'currency', glyph: 'LAK', tags: ['account'] },
  { id: 153, uniqueName: 'cur-lbp', library: 'currency', glyph: 'LBP', tags: ['account'] },
  { id: 154, uniqueName: 'cur-lkr', library: 'currency', glyph: 'LKR', tags: ['account'] },
  { id: 155, uniqueName: 'cur-lyd', library: 'currency', glyph: 'LYD', tags: ['account'] },
  { id: 156, uniqueName: 'cur-mad', library: 'currency', glyph: 'MAD', tags: ['account'] },
  { id: 157, uniqueName: 'cur-mga', library: 'currency', glyph: 'MGA', tags: ['account'] },
  { id: 158, uniqueName: 'cur-mkd', library: 'currency', glyph: 'MKD', tags: ['account'] },
  { id: 159, uniqueName: 'cur-mmk', library: 'currency', glyph: 'MMK', tags: ['account'] },
  { id: 160, uniqueName: 'cur-mnt', library: 'currency', glyph: 'MNT', tags: ['account'] },
  { id: 161, uniqueName: 'cur-mru', library: 'currency', glyph: 'MRU', tags: ['account'] },
  { id: 162, uniqueName: 'cur-mur', library: 'currency', glyph: 'MUR', tags: ['account'] },
  { id: 163, uniqueName: 'cur-mvr', library: 'currency', glyph: 'MVR', tags: ['account'] },
  { id: 164, uniqueName: 'cur-mwk', library: 'currency', glyph: 'MWK', tags: ['account'] },
  { id: 165, uniqueName: 'cur-myr', library: 'currency', glyph: 'MYR', tags: ['account'] },
  { id: 166, uniqueName: 'cur-mzn', library: 'currency', glyph: 'MZN', tags: ['account'] },
  { id: 167, uniqueName: 'cur-ngn', library: 'currency', glyph: 'NGN', tags: ['account'] },
  { id: 168, uniqueName: 'cur-nio', library: 'currency', glyph: 'NIO', tags: ['account'] },
  { id: 169, uniqueName: 'cur-omr', library: 'currency', glyph: 'OMR', tags: ['account'] },
  { id: 170, uniqueName: 'cur-pab', library: 'currency', glyph: 'PAB', tags: ['account'] },
  { id: 171, uniqueName: 'cur-pen', library: 'currency', glyph: 'PEN', tags: ['account'] },
  { id: 172, uniqueName: 'cur-pgk', library: 'currency', glyph: 'PGK', tags: ['account'] },
  { id: 173, uniqueName: 'cur-php', library: 'currency', glyph: 'PHP', tags: ['account'] },
  { id: 174, uniqueName: 'cur-pln', library: 'currency', glyph: 'PLN', tags: ['account'] },
  { id: 175, uniqueName: 'cur-pyg', library: 'currency', glyph: 'PYG', tags: ['account'] },
  { id: 176, uniqueName: 'cur-qar', library: 'currency', glyph: 'QAR', tags: ['account'] },
  { id: 177, uniqueName: 'cur-ron', library: 'currency', glyph: 'RON', tags: ['account'] },
  { id: 178, uniqueName: 'cur-rsd', library: 'currency', glyph: 'RSD', tags: ['account'] },
  { id: 179, uniqueName: 'cur-rub', library: 'currency', glyph: 'RUB', tags: ['account'] },
  { id: 180, uniqueName: 'cur-rwf', library: 'currency', glyph: 'RWF', tags: ['account'] },
  { id: 181, uniqueName: 'cur-sar', library: 'currency', glyph: 'SAR', tags: ['account'] },
  { id: 182, uniqueName: 'cur-sdg', library: 'currency', glyph: 'SDG', tags: ['account'] },
  { id: 183, uniqueName: 'cur-sll', library: 'currency', glyph: 'SLL', tags: ['account'] },
  { id: 184, uniqueName: 'cur-sos', library: 'currency', glyph: 'SOS', tags: ['account'] },
  { id: 185, uniqueName: 'cur-stn', library: 'currency', glyph: 'STN', tags: ['account'] },
  { id: 186, uniqueName: 'cur-szl', library: 'currency', glyph: 'SZL', tags: ['account'] },
  { id: 187, uniqueName: 'cur-thb', library: 'currency', glyph: 'THB', tags: ['account'] },
  { id: 188, uniqueName: 'cur-tjs', library: 'currency', glyph: 'TJS', tags: ['account'] },
  { id: 189, uniqueName: 'cur-tmt', library: 'currency', glyph: 'TMT', tags: ['account'] },
  { id: 190, uniqueName: 'cur-tnd', library: 'currency', glyph: 'TND', tags: ['account'] },
  { id: 191, uniqueName: 'cur-top', library: 'currency', glyph: 'TOP', tags: ['account'] },
  { id: 192, uniqueName: 'cur-try', library: 'currency', glyph: 'TRY', tags: ['account'] },
  { id: 193, uniqueName: 'cur-twd', library: 'currency', glyph: 'TWD', tags: ['account'] },
  { id: 194, uniqueName: 'cur-uah', library: 'currency', glyph: 'UAH', tags: ['account'] },
  { id: 195, uniqueName: 'cur-ugx', library: 'currency', glyph: 'UGX', tags: ['account'] },
  { id: 196, uniqueName: 'cur-uyu', library: 'currency', glyph: 'UYU', tags: ['account'] },
  { id: 197, uniqueName: 'cur-ves', library: 'currency', glyph: 'VES', tags: ['account'] },
  { id: 198, uniqueName: 'cur-vnd', library: 'currency', glyph: 'VND', tags: ['account'] },
  { id: 199, uniqueName: 'cur-vuv', library: 'currency', glyph: 'VUV', tags: ['account'] },
  { id: 200, uniqueName: 'cur-wst', library: 'currency', glyph: 'WST', tags: ['account'] },
  { id: 201, uniqueName: 'cur-xaf', library: 'currency', glyph: 'XAF', tags: ['account'] },
  { id: 202, uniqueName: 'cur-xof', library: 'currency', glyph: 'XOF', tags: ['account'] },
  { id: 203, uniqueName: 'cur-xpf', library: 'currency', glyph: 'XPF', tags: ['account'] },
  { id: 204, uniqueName: 'cur-zar', library: 'currency', glyph: 'ZAR', tags: ['account'] },
  { id: 205, uniqueName: 'cur-zwl', library: 'currency', glyph: 'ZWL', tags: ['account'] },
];
const ICON_BY_ID = Object.fromEntries(ICON_LIBRARY.map(i => [i.id, i]));

Object.assign(window, { ICON_LIBRARY, ICON_BY_ID });
