// ─────────────────────────────────────────────────────────────
// Icon library · IconDefinition 97 個 phosphor SVG
//
// 與 impl assets/definitions/IconDefinition.json 同步；library 全為 phosphor svg。
// SVG 檔位於 project/assets/icons/phosphor/<glyph>.svg（design git 自包副本）。
// id 1-11 為 account tag；id 12-97 為 category tag。
// ─────────────────────────────────────────────────────────────

const ICON_LIBRARY = [
  { id:  1, uniqueName: 'ph-money'                  , library: 'svg', glyph: 'money'                  , tags: ['account'] },
  { id:  2, uniqueName: 'ph-coins'                  , library: 'svg', glyph: 'coins'                  , tags: ['account'] },
  { id:  3, uniqueName: 'ph-wallet'                 , library: 'svg', glyph: 'wallet'                 , tags: ['account'] },
  { id:  4, uniqueName: 'ph-piggy-bank'             , library: 'svg', glyph: 'piggy-bank'             , tags: ['account'] },
  { id:  5, uniqueName: 'ph-jar'                    , library: 'svg', glyph: 'jar'                    , tags: ['account'] },
  { id:  6, uniqueName: 'ph-gift'                   , library: 'svg', glyph: 'gift'                   , tags: ['account'] },
  { id:  7, uniqueName: 'ph-credit-card'            , library: 'svg', glyph: 'credit-card'            , tags: ['account'] },
  { id:  8, uniqueName: 'ph-contactless-payment'    , library: 'svg', glyph: 'contactless-payment'    , tags: ['account'] },
  { id:  9, uniqueName: 'ph-paypal-logo'            , library: 'svg', glyph: 'paypal-logo'            , tags: ['account'] },
  { id: 10, uniqueName: 'ph-archive'                , library: 'svg', glyph: 'archive'                , tags: ['account'] },
  { id: 11, uniqueName: 'ph-building'               , library: 'svg', glyph: 'building'               , tags: ['account'] },
  { id: 12, uniqueName: 'ph-bread'                  , library: 'svg', glyph: 'bread'                  , tags: ['category'] },
  { id: 13, uniqueName: 'ph-coffee'                 , library: 'svg', glyph: 'coffee'                 , tags: ['category'] },
  { id: 14, uniqueName: 'ph-acorn'                  , library: 'svg', glyph: 'acorn'                  , tags: ['category'] },
  { id: 15, uniqueName: 'ph-ice-cream'              , library: 'svg', glyph: 'ice-cream'              , tags: ['category'] },
  { id: 16, uniqueName: 'ph-martini'                , library: 'svg', glyph: 'martini'                , tags: ['category'] },
  { id: 17, uniqueName: 'ph-cake'                   , library: 'svg', glyph: 'cake'                   , tags: ['category'] },
  { id: 18, uniqueName: 'ph-person-simple-bike'     , library: 'svg', glyph: 'person-simple-bike'     , tags: ['category'] },
  { id: 19, uniqueName: 'ph-bicycle'                , library: 'svg', glyph: 'bicycle'                , tags: ['category'] },
  { id: 20, uniqueName: 'ph-moped'                  , library: 'svg', glyph: 'moped'                  , tags: ['category'] },
  { id: 21, uniqueName: 'ph-motorcycle'             , library: 'svg', glyph: 'motorcycle'             , tags: ['category'] },
  { id: 22, uniqueName: 'ph-car'                    , library: 'svg', glyph: 'car'                    , tags: ['category'] },
  { id: 23, uniqueName: 'ph-bus'                    , library: 'svg', glyph: 'bus'                    , tags: ['category'] },
  { id: 24, uniqueName: 'ph-train-simple'           , library: 'svg', glyph: 'train-simple'           , tags: ['category'] },
  { id: 25, uniqueName: 'ph-taxi'                   , library: 'svg', glyph: 'taxi'                   , tags: ['category'] },
  { id: 26, uniqueName: 'ph-anchor'                 , library: 'svg', glyph: 'anchor'                 , tags: ['category'] },
  { id: 27, uniqueName: 'ph-airplane-takeoff'       , library: 'svg', glyph: 'airplane-takeoff'       , tags: ['category'] },
  { id: 28, uniqueName: 'ph-shopping-cart'          , library: 'svg', glyph: 'shopping-cart'          , tags: ['category'] },
  { id: 29, uniqueName: 'ph-storefront'             , library: 'svg', glyph: 'storefront'             , tags: ['category'] },
  { id: 30, uniqueName: 'ph-dress'                  , library: 'svg', glyph: 'dress'                  , tags: ['category'] },
  { id: 31, uniqueName: 'ph-t-shirt'                , library: 'svg', glyph: 't-shirt'                , tags: ['category'] },
  { id: 32, uniqueName: 'ph-high-heel'              , library: 'svg', glyph: 'high-heel'              , tags: ['category'] },
  { id: 33, uniqueName: 'ph-watch'                  , library: 'svg', glyph: 'watch'                  , tags: ['category'] },
  { id: 34, uniqueName: 'ph-backpack'               , library: 'svg', glyph: 'backpack'               , tags: ['category'] },
  { id: 35, uniqueName: 'ph-pencil-simple'          , library: 'svg', glyph: 'pencil-simple'          , tags: ['category'] },
  { id: 36, uniqueName: 'ph-ruler'                  , library: 'svg', glyph: 'ruler'                  , tags: ['category'] },
  { id: 37, uniqueName: 'ph-phone'                  , library: 'svg', glyph: 'phone'                  , tags: ['category'] },
  { id: 38, uniqueName: 'ph-lightbulb'              , library: 'svg', glyph: 'lightbulb'              , tags: ['category'] },
  { id: 39, uniqueName: 'ph-plugs'                  , library: 'svg', glyph: 'plugs'                  , tags: ['category'] },
  { id: 40, uniqueName: 'ph-alarm'                  , library: 'svg', glyph: 'alarm'                  , tags: ['category'] },
  { id: 41, uniqueName: 'ph-umbrella-simple'        , library: 'svg', glyph: 'umbrella-simple'        , tags: ['category'] },
  { id: 42, uniqueName: 'ph-book'                   , library: 'svg', glyph: 'book'                   , tags: ['category'] },
  { id: 43, uniqueName: 'ph-projector-screen'       , library: 'svg', glyph: 'projector-screen'       , tags: ['category'] },
  { id: 44, uniqueName: 'ph-broom'                  , library: 'svg', glyph: 'broom'                  , tags: ['category'] },
  { id: 45, uniqueName: 'ph-wrench'                 , library: 'svg', glyph: 'wrench'                 , tags: ['category'] },
  { id: 46, uniqueName: 'ph-axe'                    , library: 'svg', glyph: 'axe'                    , tags: ['category'] },
  { id: 47, uniqueName: 'ph-car-battery'            , library: 'svg', glyph: 'car-battery'            , tags: ['category'] },
  { id: 48, uniqueName: 'ph-engine'                 , library: 'svg', glyph: 'engine'                 , tags: ['category'] },
  { id: 49, uniqueName: 'ph-toilet'                 , library: 'svg', glyph: 'toilet'                 , tags: ['category'] },
  { id: 50, uniqueName: 'ph-devices'                , library: 'svg', glyph: 'devices'                , tags: ['category'] },
  { id: 51, uniqueName: 'ph-baby-carriage'          , library: 'svg', glyph: 'baby-carriage'          , tags: ['category'] },
  { id: 52, uniqueName: 'ph-armchair'               , library: 'svg', glyph: 'armchair'               , tags: ['category'] },
  { id: 53, uniqueName: 'ph-house'                  , library: 'svg', glyph: 'house'                  , tags: ['category'] },
  { id: 54, uniqueName: 'ph-music-notes-simple'     , library: 'svg', glyph: 'music-notes-simple'     , tags: ['category'] },
  { id: 55, uniqueName: 'ph-palette'                , library: 'svg', glyph: 'palette'                , tags: ['category'] },
  { id: 56, uniqueName: 'ph-camera'                 , library: 'svg', glyph: 'camera'                 , tags: ['category'] },
  { id: 57, uniqueName: 'ph-video-camera'           , library: 'svg', glyph: 'video-camera'           , tags: ['category'] },
  { id: 58, uniqueName: 'ph-ghost'                  , library: 'svg', glyph: 'ghost'                  , tags: ['category'] },
  { id: 59, uniqueName: 'ph-lego'                   , library: 'svg', glyph: 'lego'                   , tags: ['category'] },
  { id: 60, uniqueName: 'ph-game-controller'        , library: 'svg', glyph: 'game-controller'        , tags: ['category'] },
  { id: 61, uniqueName: 'ph-rocket-launch'          , library: 'svg', glyph: 'rocket-launch'          , tags: ['category'] },
  { id: 62, uniqueName: 'ph-barbell'                , library: 'svg', glyph: 'barbell'                , tags: ['category'] },
  { id: 63, uniqueName: 'ph-tennis-ball'            , library: 'svg', glyph: 'tennis-ball'            , tags: ['category'] },
  { id: 64, uniqueName: 'ph-basketball'             , library: 'svg', glyph: 'basketball'             , tags: ['category'] },
  { id: 65, uniqueName: 'ph-volleyball'             , library: 'svg', glyph: 'volleyball'             , tags: ['category'] },
  { id: 66, uniqueName: 'ph-baseball'               , library: 'svg', glyph: 'baseball'               , tags: ['category'] },
  { id: 67, uniqueName: 'ph-beach-ball'             , library: 'svg', glyph: 'beach-ball'             , tags: ['category'] },
  { id: 68, uniqueName: 'ph-ping-pong'              , library: 'svg', glyph: 'ping-pong'              , tags: ['category'] },
  { id: 69, uniqueName: 'ph-boxing-glove'           , library: 'svg', glyph: 'boxing-glove'           , tags: ['category'] },
  { id: 70, uniqueName: 'ph-football'               , library: 'svg', glyph: 'football'               , tags: ['category'] },
  { id: 71, uniqueName: 'ph-hockey'                 , library: 'svg', glyph: 'hockey'                 , tags: ['category'] },
  { id: 72, uniqueName: 'ph-person-simple-snowboard', library: 'svg', glyph: 'person-simple-snowboard', tags: ['category'] },
  { id: 73, uniqueName: 'ph-handshake'              , library: 'svg', glyph: 'handshake'              , tags: ['category'] },
  { id: 74, uniqueName: 'ph-hands-praying'          , library: 'svg', glyph: 'hands-praying'          , tags: ['category'] },
  { id: 75, uniqueName: 'ph-heart'                  , library: 'svg', glyph: 'heart'                  , tags: ['category'] },
  { id: 76, uniqueName: 'ph-pill'                   , library: 'svg', glyph: 'pill'                   , tags: ['category'] },
  { id: 77, uniqueName: 'ph-fire'                   , library: 'svg', glyph: 'fire'                   , tags: ['category'] },
  { id: 78, uniqueName: 'ph-fire-extinguisher'      , library: 'svg', glyph: 'fire-extinguisher'      , tags: ['category'] },
  { id: 79, uniqueName: 'ph-ambulance'              , library: 'svg', glyph: 'ambulance'              , tags: ['category'] },
  { id: 80, uniqueName: 'ph-clover'                 , library: 'svg', glyph: 'clover'                 , tags: ['category'] },
  { id: 81, uniqueName: 'ph-cactus'                 , library: 'svg', glyph: 'cactus'                 , tags: ['category'] },
  { id: 82, uniqueName: 'ph-tree'                   , library: 'svg', glyph: 'tree'                   , tags: ['category'] },
  { id: 83, uniqueName: 'ph-bird'                   , library: 'svg', glyph: 'bird'                   , tags: ['category'] },
  { id: 84, uniqueName: 'ph-cat'                    , library: 'svg', glyph: 'cat'                    , tags: ['category'] },
  { id: 85, uniqueName: 'ph-dog'                    , library: 'svg', glyph: 'dog'                    , tags: ['category'] },
  { id: 86, uniqueName: 'ph-bone'                   , library: 'svg', glyph: 'bone'                   , tags: ['category'] },
  { id: 87, uniqueName: 'ph-chart-line'             , library: 'svg', glyph: 'chart-line'             , tags: ['category'] },
  { id: 88, uniqueName: 'ph-bank'                   , library: 'svg', glyph: 'bank'                   , tags: ['category'] },
  { id: 89, uniqueName: 'ph-scales'                 , library: 'svg', glyph: 'scales'                 , tags: ['category'] },
  { id: 90, uniqueName: 'ph-pi'                     , library: 'svg', glyph: 'pi'                     , tags: ['category'] },
  { id: 91, uniqueName: 'ph-crown-simple'           , library: 'svg', glyph: 'crown-simple'           , tags: ['category'] },
  { id: 92, uniqueName: 'ph-planet'                 , library: 'svg', glyph: 'planet'                 , tags: ['category'] },
  { id: 93, uniqueName: 'ph-flying-saucer'          , library: 'svg', glyph: 'flying-saucer'          , tags: ['category'] },
  { id: 94, uniqueName: 'ph-rainbow'                , library: 'svg', glyph: 'rainbow'                , tags: ['category'] },
  { id: 95, uniqueName: 'ph-cigarette'              , library: 'svg', glyph: 'cigarette'              , tags: ['category'] },
  { id: 96, uniqueName: 'ph-biohazard'              , library: 'svg', glyph: 'biohazard'              , tags: ['category'] },
  { id: 97, uniqueName: 'ph-trash-simple'           , library: 'svg', glyph: 'trash-simple'           , tags: ['category'] },
];
const ICON_BY_ID = Object.fromEntries(ICON_LIBRARY.map(i => [i.id, i]));

Object.assign(window, { ICON_LIBRARY, ICON_BY_ID });
